#ifndef LEVEL_H
#define LEVEL_H

#include "room.h"

typedef struct Level { // defines a struct for a level
  Room ** rooms; // an array of pointers that will hold all of the instances of the Room struct associated with a particular level
  int xSize;
  int ySize;
  char ** levelMap; // going to hold an array of characters, that will be generated by mapSetup function that will be used to draw the level and refresh when characters, npc's and other entities move
} Level;

Level *mapSetup();
void freeLevel(Level *level);
int drawRoom(Room *room, Level *newLevel);
int connectDoors(Position * doorOne, Position * doorTwo, Level * newLevel);

#endif	/* LEVEL_H */
